### ISSUE TITLE
Error on xcute list

### ISSUE THREAD

**Issue by alessandrostone** [schwa/xcute#1]
just installed using pip and run xcute list into a project folder,
got: 
`/Volumes/Macintosh HD/Users/alessandroaresta/Documents/ELON/ELON > xcute list            master 
Traceback (most recent call last):
  File "/usr/local/bin/xcute", line 11, in <module>
    sys.exit(xcute_cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/xcute/main.py", line 23, in list
    default_xcode = Xcode.default()
  File "/usr/local/lib/python2.7/site-packages/xcute/xcode.py", line 23, in default
    Xcode.find_all()
  File "/usr/local/lib/python2.7/site-packages/xcute/xcode.py", line 41, in find_all
    Xcode._default_xcode = [xcode for version, xcode in Xcode._all_xcodes.items() if xcode.developer_dir_path == default_developer_dir_path][0]
IndexError: list index out of range`

**Comment by alessandrostone** [comment]
xcode8, swift3 project

**Comment by schwa** [comment]
Looks like it can't find Xcode… it uses spotlight (mdfind CLI tool) to find Xcode.

**Comment by schwa** [comment]
Can you run:

```/usr/bin/mdfind 'kMDItemCFBundleIdentifier="com.apple.dt.Xcode" and kMDItemContentType="com.apple.application-bundle"'```

And let me know what happens?

**Comment by alessandrostone** [comment]
results for firs command : 
/Applications/Xcode-8.app
/Applications/Xcode.app
/Applications/Xcode-beta.app

for the second the result is pretty lenghty, shall I post it here anyway?

**Comment by alessandrostone** [comment]
Nevermind, updated everything and now works flawless...
